name: ChunkBlock
version: 1.0-SNAPSHOT
main: com.jasper.chunkBlock.ChunkBlock
api-version: 1.20
authors: [Jasper]
description: A ChunkBlock plugin
softdepend: [WorldBorderAPI]
commands:
  chunk:
    description: Create or manage your chunk border
    usage: /chunk
  reload:
    description: Reloads the ChunkBlock plugin
    usage: /reload
  bypass:
