name: ChunkBlock
version: 1.0-SNAPSHOT
main: com.jasper.chunkBlock.ChunkBlock
api-version: 1.20
authors: [Jasper]
description: A ChunkBlock plugin
softdepend: [WorldBorderAPI]
depend: [WorldGuard]
commands:
  c:
    description: Main command for the ChunkBlock plugin
    usage: /<command> <subcommand>